# Generated by Django 4.2 on 2025-08-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Volunteer', 'Volunteer')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
